### ISSUE TITLE
Strange code in remove

### ISSUE THREAD

**Issue by ChrisJefferson** [fitzgen/generational-arena#3]
Hi,

While I've now convinced myself `remove` is correct, it took me a while, as it moves the value out, then puts it back if it turns out it shouldn't be removed.

I think it would be much easier to follow if instead the value was only moved out if it will be returned. Is there any reason for the back-and-forth (like it's faster?)

**Comment by fitzgen** [comment]
I *think* I did it this way because otherwise there would be borrowck errors when trying to remove the entry while in a match arm that matches that same entry. I don't know if I actually tried doing it that way and got the error or just anticipated getting it. You could try changing it and finding out if it works or not!

**Comment by fitzgen** [comment]
And thanks :)
